name: Deploy

on:
  push:
    branches:
      - master

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-20.04
    steps:
      # Clone the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Build Docker image
      - name: Docker build
        run: docker login --username=kuezster --password=$HEROKU_API_KEY registry.heroku.com

      # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          heroku container:push web -a ${{ $HEROKU_APP_NAME }}
          heroku container:release web -a ${{ $HEROKU_APP_NAME }}
